### ISSUE TITLE
video stream流 能否选择硬件解码播放？

### ISSUE THREAD

**Issue by yilun-zhangs** [zuguorui/Android-VideoPlayer#2]

**Comment by zuguorui** [comment]
@yilun-zhangs 在
`bool FFmpegCodec::init(AVCodecParameters *params, PreferCodecType preferType, bool isEncoder)`
中设置preferType即可选择硬解还是软解。当前逻辑是NONE，优先硬解，然后软解。不过需要注意的是很多音频是不支持硬解的，所以当前使用NONE，视频已经是优先硬解了。
